<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Intersect.Client.Web</RootNamespace>
    <AssemblyName>Intersect Client Web</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Intersect (Core)\Intersect.Core.csproj" />
    <ProjectReference Include="..\Intersect.Client.Core\Intersect.Client.Core.csproj" />
    <ProjectReference Include="..\Intersect.Client.Framework\Intersect.Client.Framework.csproj" />
    <ProjectReference Include="..\Intersect.Network\Intersect.Network.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.11" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Intersect Client Core</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
