<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>AscensionGameDev.Intersect.Client.Core</PackageId>
    <Description>Game Client Core - Part of the Intersect 2D Game Creation Suite</Description>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <RootNamespace>Intersect.Client</RootNamespace>
    <AssemblyName>Intersect Client Core</AssemblyName>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Intersect.Tests.Client</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Intersect.SinglePlayer</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Intersect Client</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Intersect Client MonoGame</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Intersect Client Web</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Intersect (Core)\Intersect.Core.csproj" />
    <ProjectReference Include="..\Intersect.Client.Framework\Intersect.Client.Framework.csproj" />
    <ProjectReference Include="..\Intersect.Network\Intersect.Network.csproj" />
  </ItemGroup>

</Project>
